In [1]:
import numpy as np

In [2]:


matriz = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("Elemento na linha 1, coluna 2:", matriz[1, 2])
print("Primeira linha inteira:", matriz[0, :])
print("Segunda coluna inteira:", matriz[:, 1])
print("Sub-matriz (linhas 0-1, colunas 1-2):\n", matriz[0:2, 1:3])

# Indexação booleana
print("Valores maiores que 5:", matriz[matriz > 5])

# Broadcasting: somando um vetor a cada linha da matriz
vetor = np.array([10, 20, 30])
print("Broadcasting (matriz + vetor):\n", matriz + vetor)

Elemento na linha 1, coluna 2: 6
Primeira linha inteira: [1 2 3]
Segunda coluna inteira: [2 5 8]
Sub-matriz (linhas 0-1, colunas 1-2):
 [[2 3]
 [5 6]]
Valores maiores que 5: [6 7 8 9]
Broadcasting (matriz + vetor):
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
