In [1]:
import numpy as np

vetor = np.array([1, 2, 3])
matriz = np.array([[1, 2, 3], [4, 5, 6]])
zeros = np.zeros((2, 3))
sequencia = np.arange(0, 10, 2)
espacados = np.linspace(0, 1, 5)

print("Vetor (1D):", vetor, "shape:", vetor.shape)
print("Matriz (2D):\n", matriz, "shape:", matriz.shape)
print("Array de zeros:\n", zeros)
print("Sequência com passo 2:", sequencia)
print("5 valores igualmente espaçados entre 0 e 1:", espacados)
print("Tipo de dado (dtype):", matriz.dtype)

Vetor (1D): [1 2 3] shape: (3,)
Matriz (2D):
 [[1 2 3]
 [4 5 6]] shape: (2, 3)
Array de zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Sequência com passo 2: [0 2 4 6 8]
5 valores igualmente espaçados entre 0 e 1: [0.   0.25 0.5  0.75 1.  ]
Tipo de dado (dtype): int64


O coração do NumPy é o ndarray – um container que organiza dados em grades (arrays multidimensionais). A dimensão dele define o jogo: 1D é uma fila de números, 2D é uma tabela com linhas e colunas (matriz) e 3D é uma pilha dessas tabelas empilhadas (tensor). Pra entender o formato, a gente olha os atributos: shape mostra o tamanho em cada eixo, ndim conta quantos eixos existem, size dá o total de elementos e dtype revela o tipo dos números lá dentro. Ao contrário das listas do Python, todo mundo dentro de um array precisa ser do mesmo tipo – isso que deixa as operações rápidas porque a memória fica contínua. Pra criar arrays, temos as funções que tão no código: np.array() pra conversão direta, np.zeros() pra iniciar com zeros, np.arange() pra sequências com passo e np.linspace() pra divisões exatas de intervalo (além de outras como np.ones(), que não tão no exemplo, mas completam o time).

 A primeira coisa é importar a biblioteca com import numpy as np – isso é padrão, todo mundo usa esse apelido np pra não ter que digitar numpy toda hora.

In [2]:
vetor = np.array([1, 2, 3])

Essa é uma lista simples com 3 números. Como só tem um par de colchetes, isso vira um array 1D – ou seja, uma fila de números. Lá no print, quando rodar vetor.shape, ele vai devolver (3,). Repara-se uma vírgula ali, isso é a forma que o Python tem de dizer "isso é uma tupla com um único elemento", indicando que ele só tem 3 posições nessa dimensão única.

In [3]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

Agora temos dois pares de colchetes: um para a linha de cima e outro para a de baixo. Isso é um array 2D (matriz). O shape dela vai ser (2, 3), que significa "2 linhas e 3 colunas". O print já vai mostrar ela formatada com uma linha em cima da outra.

In [4]:
zeros = np.zeros((2, 3))

 O np.zeros já cria uma matriz 2x3 (porque passamos (2, 3) dentro dos parênteses) totalmente preenchida com o número 0. No print, é possível ver duas linhas, cada uma com [0. 0. 0.] – repara que ele coloca o ponto decimal porque, internamente, o NumPy entende que isso é float.

In [5]:
sequencia = np.arange(0, 10, 2)


Essa função é parecida com o range() do Python puro. O 0 é o início, o 10 é o limite (que não entra) e o 2 é o passo. Ou seja, ele vai gerar os números 0, 2, 4, 6, 8. O print vai mostrar exatamente [0 2 4 6 8].



In [6]:
espacados = np.linspace(0, 1, 5)

Agora, diferente do arange que vai pulando de 2 em 2, o linspace divide o intervalo de 0 até 1 em 5 partes iguais. Ele sempre inclui o início e o fim. O resultado no print vai ser [0. 0.25 0.5 0.75 1.], porque ele calculou exatamente o espaçamento entre eles.

Por fim, o último print pega o matriz.dtype. Ele vai olhar para aquela matriz 2x3 que a gente criou com números inteiros (1, 2, 3, 4, 5, 6) e vai mostrar qual o tipo daquele dado.